{% set name = "CherryPy" %}
{% set version = "11.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "2131a96120baede76873b0b5a7d1df0bebb21ab3e01a579ccc6a6f5844918664" %}
{% set build = 0 %}

package:
  skip: True  # [win32]
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - cherryd = cherrypy.__main__:run
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - setuptools
    - six >=1.11.0
    - cheroot >=5.8.3
    - portend >=2.1.1
    - jaraco.classes

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Object-Oriented HTTP framework'
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
