{% set name = "CherryPy" %}
{% set version = "14.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "5f5ee020d6547a8d452b3560775ca2374ffe2ff8c0aec1b272e93b6af80d850e" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - cherryd = cherrypy.__main__:run
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools_scm

  run:
    - python
    - setuptools
    - six >=1.11.0
    - cheroot >=5.8.3
    - portend >=2.1.1
    - jaraco.classes

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Object-Oriented HTTP framework'
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
