{% set name = "CherryPy" %}
{% set version = "10.2.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "2ee7e514de0167b63233a6bba25dda2bb9d5ef800da8ea3a0282a9a57a382274" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
      - cherryd = cherrypy.__main__:run
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - six
    - cheroot >=5.2.0
    - portend >=1.6.1
    - simplejson
    - routes >=2.3.1
    - pyopenssl
    - python-memcached >=1.58
    - flup

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial
    - cherrypy.wsgiserver

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license_file: cherrypy/LICENSE.txt
  license: BSD 3-Clause
  license_family: BSD
  summary: Object-Oriented HTTP framework
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
