# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "18.10.0"
  python_check_max: "3.14"
  pytest_k: not queue_full
  cov_fail_under: "73"

package:
  name: cherrypy
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/c/cherrypy/cherrypy-${{ version }}.tar.gz
  sha256: 6c70e78ee11300e8b21c0767c542ae6b102a49cac5cfd4e3e313d7bb907c5891

build:
  number: 3
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check --check-build-dependencies
  python:
    entry_points:
      - cherryd = cherrypy.__main__:run

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm >=7
  run:
    - cheroot >=8.2.1
    - jaraco.collections
    - more-itertools
    - portend >=2.1.1
    - pyopenssl
    - python >=${{ python_min }}
    - pywin32 >=227
    - routes >=2.3.1
    - simplejson
    - zc.lockfile

tests:
  - package_contents:
      strict: true
      site_packages:
        - cherrypy/**
        - cherrypy-${{ version }}.dist-info/**
  - python:
      imports: cherrypy
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - objgraph
        - path
        - pytest-cov
        - pytest-services >=2
        - python ${{ python_min }}.*
        - requests-toolbelt
        - setuptools
    script:
      - cherryd -h
      - coverage run --source=cherrypy --branch -m pytest -vv --tb=long --color=yes --pyargs cherrypy -k "${{ pytest_k }}"
      - coverage report --show-missing --skip-covered --fail-under=${{ cov_fail_under }}

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Object-Oriented HTTP framework
  description: |
    CherryPy is a pythonic, object-oriented web framework.
    It allows developers to build web applications in much the same way they would
    build any other object-oriented Python program. This results in smaller source
    code developed in less time.
  homepage: https://pypi.org/project/cherrypy
  repository: https://github.com/cherrypy/cherrypy
  documentation: https://docs.cherrypy.dev

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
    - bollwyvl
