# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "OqnxVMVYx9JvPJGlBVFn+f9uKF63NgaaD6shzaoguOAAL8QkIJasGCkzzp+iNSesypJQ0qc7gRLMaoQXRVPV0IkfnrVzvvOg4KFLTrzR8mFr68TbfhaXXDw6TV738cIEA4DOouw+yx844UyIbeISnCc0MMsbXsVqIlOA+7goiqOQN0ER44JUbIWOI9TKbrnqTzyrWhQtmwi0Vn9UFfldQBLjkfUKOZQz1J1ZfGpfbuCNuHcslI9kJ1xMTz6eqX3H7qIXSbzRvW8ZdWHjJ50TDtWgPICkgBmtRNOm99594wqqhdpLZ7/absJagaDyuVcmjLKLZ1c04nkaHr0EG55JbvRZWms9TJqJI65rjFsSyJAfgM13q26RUk28T/+8TWY0tFNspaRbb+rAniD5tXEAL05RCfpirstLItQ8j/GZ9Oo3vcmQt5F0+KwM1dE0IJ4aFWatLpMtpxfFrD9xVmMVPgE/OVSr34vLVYbxf9MTkkgFjQXKj0uWGIwBly0aeLEdaJ0c2+FiEr7MesMLrLeXTXS5a6wFJcrR/VqQq9HW753xkzqnNxiyv5cn/NNY/wjXsIW7ePlfIpWsGFDQpDP5Cgx4ahakg1SwFZAb37C5q1ccToN/6DImna+339TC/vXdK4aHCLFaE8ETfodvGXB8vhWa/6KGYRzrnS7AILkshQ8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
