appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: UNqqWAgsXvBz/iSs4DzKxoLF/5NhOi87Yl9tqn5OZk+1lWORtkxSyKirWQWcZOjBNFdQ/EpO85P0ewZotdLQSAZ5Vy798qJ0avXDu2YHRuL6qnbFqJQGELLJCr0l2sNtGoNIfUaLx8sE3uvmFXjgp84Wx/YCosq9jXIVYfe7/XXnVcbPJJu2VfYRkS1VdkNJsFiiNf1Y5zXTDIW2S4K4g9U+/RGc5QLLfmfGjaQfzmgW2kfGn2dR03g8Ofb6yL+p1kRUR3DgG9LD5213pks3imxTNSpIn8jpiZZRQvbOVKBlnwjvCsjQCboZGwFS5pdEI6H9Z8A6fJsknbmxvT4N1/p4eSQly72hV6C8okbESmU44DzrtBpuwn0hYXffZUK4mIsOJiEBF3t301jKr5tH0EoxeBQ643HSHLKprlcUTcIWA4WRXIg/I/ctM1wH9LlLQbhR0HMwIAo0DSrhw+xPiJyCR0RpQURFz/eFCWjO6aH8jkGG+45k/6hDdXUvvD7FfLIB4kho2lOtM11ocoJZJTZoyLsIfRWWOjt68USPoS9E1nZkebcopFjFuKZxexER3idVsfD0b5alIl2MhdwgU2ewaPOsB2O/qe7tzsqHMjppwNTH4Ybtclrl/V7sPW9p4rF3C2DUsxuLg/rsqyfk9E2mSnhk2u0MX1jsB5oFsfU=}
provider:
  win: azure
